# Site settings
title: Erik Öhrn
description: A quick intro to a guy who enjoys coding, designing, tech, and snapping pictures
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://erikohrn.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Erik Öhrn
user_description: With experience gathered from multiple tech work places, my years at Chalmers University of Technology, and several volunteering projects, I’m comfortable working with technology as well as the people it’s made for.
user_title: Software developer, user experience designer, photographer
email: erik@erikohrn.com
#twitter_username: lorem_ipsum
github_username:  oherik
linkedin_username:  erik-öhrn-a2630664
flickr_username: ohrn.erik
flickr_portfolio: https://www.flickr.com/photos/131689120@N03/albums/72157695820916651
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
